services:
  materia-care:
    container_name: materia-care
    image: materia-care:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:39066:80"
    restart: unless-stopped
